### ISSUE TITLE
Proxy Connection Failed in Edge

### ISSUE THREAD

**Issue by ejschenck** [hensm/mullvad-proxy#24]
I'm running Edge on macOS Ventura with an M1 MacBook Pro.  The extension works fine on Firefox, but on Edge no matter what I select I get an error:
"Proxy Connection Failed.  Could not connect to… <insert proxy server here>"

![CleanShot 2022-08-15 at 14 57 36@2x](https://user-images.githubusercontent.com/18517556/184698746-1dc265d3-3a74-409e-aa7f-90d8e7aa67f7.png)

**Comment by hensm** [comment]
Looks like the API changed. The SOCKS hostnames used to be provided without the `.mullvad.net` suffix, which is why it's doubled up in your screenshot.

I've fixed this and uploaded a new Firefox version for review, but I'm not going to update the Edge version for now since their review process is kinda tedious and they've stopped accepting Manifest V2 extensions apparently, which probably means some bigger changes.

Here's a packaged version you can sideload, though:
[mullvad_proxy_unofficial_-0.2.4.zip](https://github.com/hensm/mullvad-proxy/files/9343839/mullvad_proxy_unofficial_-0.2.4.zip)

**Comment by ejschenck** [comment]
@hensm Thank you so much for the prompt response!  Added the extension to Edge and it's working fine.  You rock!
