### ISSUE TITLE
does not detect mullvad running maybe api change 

### ISSUE THREAD

**Issue by lordthor** [hensm/mullvad-proxy#25]
app is broken as of today 9-25-22. just goes round and round and says not connected maybe mullvad changed api again but yeah i would really appricate if you could update and fix this problem i have the problem in firefox and edge and it just goes round and round and says not connected. then it just does not give any options.

**Comment by hensm** [comment]
I don't see any obvious API changes, but I can't test anything since I don't have any time on my Mullvad account at the moment. Some logs from the [browser console](https://firefox-source-docs.mozilla.org/devtools-user/browser_console/index.html) or [extension toolbox](https://extensionworkshop.com/documentation/develop/debugging/#developer-tools-toolbox) could be useful.

**Comment by lordthor** [comment]
its working again app was down for a day but does not really work in edge but works on firefox

**Comment by hensm** [comment]
Yeah, the Edge version is broken and I had issues trying to publish an update last time I tried.

There's a build you can side load [here](https://github.com/hensm/mullvad-proxy/issues/24#issuecomment-1216001708).
